# log
log:
  version: 1
  disable_existing_loggers: true
  formatters:
    simple:
      format: '[%(levelname)s] %(asctime)s| %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: simple
      filename: logs/log.log
  loggers:
    simpleExample:
      level: DEBUG
      handlers: [console]
      propagate: no
  root:
    level: DEBUG
    handlers: [console,file]